"""
Sample PDF Generator — Doc 2: Styled / Medium Complexity
100 requirements with bolded section numbers, colour-coded level bands,
headers and footers on each page, a title page, and a ruled table of contents stub.
Tests pdfplumber's ability to handle page headers/footers, mixed font weights,
and coloured backgrounds without being misled by decorative elements.
"""

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm, mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak,
    HRFlowable
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from reportlab.lib import colors
from reportlab.platypus.doctemplate import PageTemplate, BaseDocTemplate
from reportlab.platypus.frames import Frame
import os

OUTPUT_PATH = os.path.join(os.path.dirname(__file__), "../sample-pdfs/sample_02_styled.pdf")

# Level band colours (light tints) — each top-level section gets a colour stripe
LEVEL_COLORS = {
    1: colors.HexColor("#E8F0FE"),  # blue tint
    2: colors.HexColor("#E6F4EA"),  # green tint
    3: colors.white,
    4: colors.white,
    5: colors.white,
    6: colors.white,
}

REQUIREMENTS = [
    # Section 1 — Performance
    ("1", "The system shall meet the performance thresholds defined in this section under all specified operational load conditions."),
    ("1.1", "The system shall process a standard search query and return results within 1.5 seconds at the 95th percentile under nominal load."),
    ("1.1.1", "Nominal load is defined as up to 200 concurrent active users submitting queries at a rate not exceeding 10 queries per second per user."),
    ("1.1.1.1", "The 95th percentile response time measurement shall be collected using distributed tracing instrumentation on the application server."),
    ("1.1.1.1.1", "Distributed tracing shall use the OpenTelemetry standard and export to the organisation's approved observability platform."),
    ("1.1.1.1.1.1", "The OpenTelemetry exporter configuration shall support runtime update without requiring a service restart."),
    ("1.2", "The system shall sustain a throughput of at least 500 transactions per second for bulk data import operations."),
    ("1.2.1", "Throughput measurement shall be performed using the standard load test suite defined in the project test plan."),
    ("1.2.1.1", "The load test suite shall simulate realistic data payloads drawn from the production data sample set."),
    ("1.2.1.1.1", "Production data samples used in load testing shall be anonymised in accordance with the organisation's data handling policy."),
    ("1.2.1.1.1.1", "Anonymisation shall replace all personally identifiable fields with synthetic data generated by the approved data masking tool."),
    ("1.3", "The system shall recover from a single application server failure and resume processing within 60 seconds without data loss."),
    ("1.3.1", "Recovery shall be verified by the automated failover test in the CI pipeline before each production deployment."),
    ("1.3.1.1", "The automated failover test shall simulate failure by sending a SIGKILL signal to a randomly selected application server instance."),
    # Section 2 — Security
    ("2", "The system shall implement security controls that meet the requirements of ISO/IEC 27001:2022 and the organisation's information security policy."),
    ("2.1", "The system shall encrypt all data in transit using TLS 1.3 or higher."),
    ("2.1.1", "TLS certificate management shall be automated using the organisation's PKI certificate authority."),
    ("2.1.1.1", "Certificates shall be renewed automatically at least 30 days before expiry using an ACME-compliant renewal agent."),
    ("2.1.1.1.1", "The renewal agent shall send an alert to the security team if automatic renewal fails more than 5 days before certificate expiry."),
    ("2.1.1.1.1.1", "The alert shall be delivered via the organisation's monitoring platform and shall trigger a Priority 1 incident ticket."),
    ("2.2", "The system shall encrypt all data at rest using AES-256 with keys managed by the organisation's key management service."),
    ("2.2.1", "Key rotation shall occur automatically on a 365-day cycle or immediately following a suspected key compromise event."),
    ("2.2.1.1", "The key management service shall maintain an audit log of all key creation, rotation, and deletion events."),
    ("2.2.1.1.1", "The audit log shall be stored in a write-once, append-only storage system to prevent tampering."),
    ("2.2.1.1.1.1", "Write-once storage shall be implemented using the S3 Object Lock feature with Compliance mode and a 7-year retention period."),
    ("2.3", "The system shall implement role-based access control (RBAC) with a minimum of four roles: Viewer, Editor, Approver, and Administrator."),
    ("2.3.1", "Role assignments shall be managed exclusively through the identity provider and shall not be editable within the application."),
    ("2.3.1.1", "The application shall re-read role assignments from the identity provider at each session establishment."),
    # Section 3 — Usability
    ("3", "The system shall meet usability requirements as validated by a representative sample of end users during acceptance testing."),
    ("3.1", "The system shall conform to WCAG 2.1 Level AA accessibility standards for all web-based interfaces."),
    ("3.1.1", "Accessibility conformance shall be verified using an automated accessibility scanning tool as part of the CI pipeline."),
    ("3.1.1.1", "The CI accessibility scan shall flag any new WCAG 2.1 Level AA violation as a build failure."),
    ("3.1.1.1.1", "Exceptions to the build failure rule may be approved by the accessibility lead and recorded in the exception register."),
    ("3.1.1.1.1.1", "Each exception entry shall include: the violated criterion, the justification, the approving authority, and an expected resolution date."),
    ("3.2", "The system shall allow a first-time user to complete the standard onboarding workflow without external assistance within 15 minutes."),
    ("3.2.1", "The onboarding workflow is defined as: account creation, first login, completion of the guided project setup wizard, and creation of the first requirement artefact."),
    ("3.2.1.1", "The guided project setup wizard shall consist of no more than 5 steps, each displayed on a dedicated screen."),
    ("3.2.1.1.1", "Each wizard step shall display contextual help text and a link to the relevant section of the user documentation."),
    ("3.2.1.1.1.1", "User documentation links in the wizard shall be validated automatically in the CI pipeline to detect broken links before each release."),
    # Section 4 — Integration
    ("4", "The system shall provide integration interfaces supporting data exchange with IBM Engineering Lifecycle Management tools."),
    ("4.1", "The system shall expose an OSLC Requirements Management 2.0 compliant API for integration with external tools."),
    ("4.1.1", "The OSLC API shall support creation, retrieval, update, and deletion of requirement resources."),
    ("4.1.1.1", "OSLC resource creation shall return an HTTP 201 Created response with the new resource URL in the Location header."),
    ("4.1.1.1.1", "The Location header URL shall be stable and shall not change if the resource is subsequently moved within the project hierarchy."),
    ("4.1.1.1.1.1", "Resource URL stability shall be maintained through a redirect mechanism if an internal ID change is required due to module restructuring."),
    ("4.2", "The system shall support import and export of requirements in ReqIF 1.0.1 format."),
    ("4.2.1", "The ReqIF export shall include all custom attribute definitions and their enumeration value sets."),
    ("4.2.1.1", "Enumeration value sets shall be exported as ReqIF DATATYPE-DEFINITION-ENUMERATION elements."),
    ("4.2.1.1.1", "The export shall preserve the display order of enumeration values as configured in the project type system."),
    ("4.2.1.1.1.1", "If the importing tool does not support ordered enumerations, the system shall log a compatibility warning in the export report."),
    ("4.3", "The system shall provide webhook notifications for requirement creation, modification, and deletion events."),
    ("4.3.1", "Webhook payloads shall be delivered within 5 seconds of the triggering event under normal system load."),
    ("4.3.1.1", "Failed webhook deliveries shall be retried using exponential backoff with a maximum of 5 retry attempts."),
    ("4.3.1.1.1", "After 5 failed attempts, the webhook endpoint shall be automatically disabled and the project administrator notified."),
    ("4.3.1.1.1.1", "The administrator notification shall include the webhook URL, the failure count, and the last HTTP error code received."),
    # Section 5 — Data Management
    ("5", "The system shall implement data management policies ensuring durability, integrity, and recoverability of all requirements data."),
    ("5.1", "The system shall perform automated database backups at a minimum frequency of once every 24 hours."),
    ("5.1.1", "Each backup shall be verified by an automated restore test to a separate test environment within 4 hours of completion."),
    ("5.1.1.1", "The restore test shall verify that all requirement records, traceability links, and baseline snapshots are present and consistent."),
    ("5.1.1.1.1", "Consistency verification shall include a checksum comparison between the source database and the restored copy."),
    ("5.1.1.1.1.1", "If the checksum comparison fails, the backup shall be marked as invalid and a new backup shall be triggered immediately."),
    ("5.2", "The system shall maintain a full audit trail of all data modifications for a minimum retention period of 7 years."),
    ("5.2.1", "The audit trail shall be immutable — no user or administrator shall be able to delete or modify audit entries."),
    ("5.2.1.1", "Immutability shall be enforced at the storage layer, not solely through application-level access controls."),
    ("5.2.1.1.1", "The storage layer immutability mechanism shall be validated by an annual penetration test."),
    ("5.2.1.1.1.1", "Penetration test findings related to audit trail integrity shall be classified as Critical severity and remediated within 30 days."),
    ("5.3", "The system shall detect and alert on data integrity violations such as orphaned traceability links or missing parent artefacts."),
    ("5.3.1", "Integrity checks shall run automatically every 6 hours and after every bulk import operation."),
    ("5.3.1.1", "Each integrity check run shall produce a report listing all violations found, their severity, and recommended corrective action."),
    # Section 6 — Deployment
    ("6", "The system shall be deployable on-premise and on major cloud platforms including AWS, Azure, and Google Cloud Platform."),
    ("6.1", "The system shall be packaged as OCI-compliant container images with all dependencies included."),
    ("6.1.1", "Container images shall be scanned for known vulnerabilities using an approved image scanning tool before each deployment."),
    ("6.1.1.1", "Images with Critical or High CVE severity findings shall not be deployed to production without an approved risk acceptance."),
    ("6.1.1.1.1", "Risk acceptances shall be documented in the security register and approved by the CISO or designated delegate."),
    ("6.1.1.1.1.1", "Each risk acceptance shall have a maximum validity period of 90 days after which it must be re-evaluated."),
    ("6.2", "The system shall support horizontal scaling by adding or removing application server instances without service interruption."),
    ("6.2.1", "Autoscaling policies shall be provided as Infrastructure-as-Code templates for Kubernetes HorizontalPodAutoscaler."),
    ("6.2.1.1", "The autoscaling configuration shall define scale-up and scale-down thresholds based on CPU utilisation and request queue depth."),
    ("6.2.1.1.1", "Scale-up shall trigger when CPU utilisation exceeds 70% or queue depth exceeds 1000 requests for more than 60 seconds."),
    ("6.2.1.1.1.1", "The autoscaling evaluation interval shall be configurable and shall default to 15 seconds."),
    ("6.3", "The system shall provide a health check endpoint that returns HTTP 200 when all critical subsystems are operational."),
    ("6.3.1", "The health check shall verify connectivity to the database, the identity provider, and the key management service."),
    ("6.3.1.1", "Each subsystem check within the health endpoint shall complete within 500ms to avoid false negatives under load."),
    ("6.3.1.1.1", "If a subsystem check times out, the health endpoint shall return HTTP 503 and include the name of the failing subsystem in the response body."),
    ("6.3.1.1.1.1", "The HTTP 503 response body shall conform to the RFC 7807 Problem Details JSON format."),
    # Section 7 — Reporting
    ("7", "The system shall provide built-in reporting capabilities covering requirements coverage, traceability status, and change history."),
    ("7.1", "The system shall provide a Requirements Traceability Matrix (RTM) report exportable in CSV and PDF formats."),
    ("7.1.1", "The RTM shall include all requirements in the selected module and shall show linked test cases and their current execution status."),
    ("7.1.1.1", "Execution status shall reflect the most recent test run result at the time the report is generated."),
    ("7.1.1.1.1", "The report generation timestamp shall be included in the report header to allow assessment of result currency."),
    ("7.1.1.1.1.1", "Report timestamps shall use ISO 8601 format in UTC timezone."),
    ("7.2", "The system shall provide a change history report showing all modifications to requirements within a specified date range."),
    ("7.2.1", "The change history report shall be filterable by requirement ID, modifying user, date range, and attribute changed."),
    ("7.2.1.1", "Filter combinations shall be applied using AND logic; OR filtering shall not be required."),
    ("7.2.1.1.1", "The user interface for the change history filter shall display the number of matching records before the report is generated."),
    ("7.2.1.1.1.1", "The record count preview shall update dynamically as the user adjusts filter parameters without requiring a full page reload."),
]


def header_footer(canvas, doc):
    canvas.saveState()
    width, height = A4
    # Header
    canvas.setFont("Helvetica-Bold", 9)
    canvas.setFillColor(colors.HexColor("#2C3E50"))
    canvas.drawString(2.5 * cm, height - 1.5 * cm, "SAMPLE REQUIREMENTS SPECIFICATION — DOCUMENT 2 (STYLED)")
    canvas.setFont("Helvetica", 9)
    canvas.drawRightString(width - 2.5 * cm, height - 1.5 * cm, f"CONFIDENTIAL")
    canvas.setStrokeColor(colors.HexColor("#2C3E50"))
    canvas.setLineWidth(0.5)
    canvas.line(2.5 * cm, height - 1.7 * cm, width - 2.5 * cm, height - 1.7 * cm)
    # Footer
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.grey)
    canvas.line(2.5 * cm, 1.8 * cm, width - 2.5 * cm, 1.8 * cm)
    canvas.drawString(2.5 * cm, 1.2 * cm, "FOR TEST USE ONLY — pdfplumber parsing demo")
    canvas.drawCentredString(width / 2, 1.2 * cm, f"Page {doc.page}")
    canvas.restoreState()


def build_pdf(output_path):
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=2.5 * cm,
        rightMargin=2.5 * cm,
        topMargin=3.0 * cm,
        bottomMargin=2.5 * cm,
    )

    styles = getSampleStyleSheet()

    story = []

    # Title page
    story.append(Spacer(1, 3 * cm))
    story.append(Paragraph("System Requirements Specification", ParagraphStyle(
        "BigTitle", fontSize=22, fontName="Helvetica-Bold", alignment=TA_CENTER, spaceAfter=12
    )))
    story.append(Paragraph("Document 2 — Styled Format (Medium Complexity)", ParagraphStyle(
        "SubTitle", fontSize=14, fontName="Helvetica", alignment=TA_CENTER, spaceAfter=6, textColor=colors.HexColor("#555555")
    )))
    story.append(Spacer(1, 1 * cm))
    meta = [
        ["Document No.", "SRS-SAMPLE-002"],
        ["Version", "2.1"],
        ["Status", "For Test Use Only"],
        ["Classification", "CONFIDENTIAL"],
        ["Date", "2025-06-24"],
    ]
    t = Table(meta, colWidths=[5 * cm, 8 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#2C3E50")),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.white),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("ROWBACKGROUNDS", (1, 0), (1, -1), [colors.HexColor("#F0F0F0"), colors.white]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(t)
    story.append(PageBreak())

    # Requirements
    for section_num, req_text in REQUIREMENTS:
        level = section_num.count(".") + 1
        indent = (level - 1) * 0.5 * cm
        bg = LEVEL_COLORS.get(level, colors.white)

        if level <= 2:
            cell_style = ParagraphStyle(
                f"S{level}",
                fontSize=10 if level == 2 else 11,
                fontName="Helvetica-Bold",
                leftIndent=indent,
                spaceAfter=4,
                spaceBefore=4,
            )
        else:
            cell_style = ParagraphStyle(
                f"S{level}",
                fontSize=10,
                fontName="Helvetica",
                leftIndent=indent,
                spaceAfter=3,
            )

        row_table = Table(
            [[Paragraph(f"<b>{section_num}</b>", ParagraphStyle("N", fontSize=10, fontName="Helvetica-Bold")),
              Paragraph(req_text, cell_style)]],
            colWidths=[2.2 * cm, 13.3 * cm],
        )
        row_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), bg),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("LINEBELOW", (0, 0), (-1, -1), 0.25, colors.HexColor("#CCCCCC")),
        ]))
        story.append(row_table)

    doc.build(story, onFirstPage=header_footer, onLaterPages=header_footer)
    print(f"Created: {output_path}")


if __name__ == "__main__":
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    build_pdf(OUTPUT_PATH)
